 # Global settings - most REQUIRED
time_framework = [2020, 2025, 2030, 2035, 2040, 2045, 2050]
foresight = 5   # Has to be a multiple of the minimum separation between the years in time framework
regions = ["R1"]
interest_rate = 0.1
interpolation_mode = 'Active'
log_level = 'info'

# Convergence parameters
equilibrium_variable = 'demand'
maximum_iterations = 100
tolerance = 0.1
tolerance_unmet_demand = -0.1

[[outputs]]
quantity = "prices"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[[outputs]]
quantity = "capacity"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"
index = false
keep_columns = ['technology', 'dst_region', 'region', 'agent', 'sector', 'type', 'year', 'capacity']

# Carbon budget control
[carbon_budget_control]
budget = []

[global_input_files]
projections = '{path}/input/Projections.csv'
global_commodities = '{path}/input/GlobalCommodities.csv'

[sectors.hydrogen]
type = 'default'
priority = 1
dispatch_production = 'share'

technodata = '{path}/technodata/hydrogen/Technodata.csv'
commodities_in = '{path}/technodata/hydrogen/CommIn.csv'
commodities_out = '{path}/technodata/hydrogen/CommOut.csv'

[sectors.hydrogen.subsectors.retro_and_new]
agents = '{path}/technodata/Agents.csv'
existing_capacity = '{path}/technodata/hydrogen/ExistingCapacity.csv'
lpsolver = "adhoc"  # Optional, defaults to "adhoc" 

[[sectors.hydrogen.outputs]]
filename = '{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}'
quantity = "capacity"
sink = 'csv'
overwrite = true
index = false

[[sectors.hydrogen.interactions]] 
net = 'new_to_retro'
interaction = 'transfer'

[sectors.hydrogen_presets]
type = 'presets'
priority = 0
demand_path= "{path}/technodata/preset/Demand.csv"